### PR TITLE
Update to numpy 2.x

### PR DESCRIPTION
**Pull request by lrauschning**
Hi all,
updated the codebase to work with numpy 2.x .
Also had a look at the CI – the current CI failure seems to be caused by pypairix breaking on compile, commenting the dependency out makes it run. Have submitted an issue there and propose adding it again when that is fixed.
Currently, some test cases in `test_cli_ingest.py` and `test_create_ingest.py` are returning different values than stored in `tests/data`.
Not sure what's causing that, as the numpy update shouldn't change behaviour in this way. Might be the missing pypairix dependency, or an earlier change that wasn't noticed due to the general CI failure?
In a local pipeline using cooler I don't see any changes, so I think this should be fine to merge anyways, though it would be nice to get CI passing.
Cheers and happy winter holidays,
Leon

### CODE REVIEW

**Comment by nvictus** [comment]
Thank you for the PR and thank you for submitting the issue upstream!

I'm currently traveling but will look into the odd test cases when I have some time.

**Comment by lrauschning** [comment]
Thanks, have a nice winter break!

**Comment by nvictus** [comment]
The test errors were actually caused by a strange behavioral change starting in numpy 2.1. Applying `np.array()` to a pandas Series no longer produces a proper copy of the data even when `copy=True`. As a result, some in-place operations on the array were mutating the underlying dataframe. This seems like a bug, though perhaps numpy's semantics of "shallow" copying have changed.

I switched to the pandas method `Series.to_numpy(copy=True)`, which guarantees a true copy.

**Comment by nvictus** [comment]
> the current CI failure seems to be caused by pypairix breaking on compile, commenting the dependency out makes it run. Have submitted an issue there and propose adding it again when that is fixed.

I agree with dropping pairix from the `[all]` extra until a fix is released. FWIW, this [PR](https://github.com/4dn-dcic/pairix/pull/78) seems to resolve the compilation issue, at least for me.

**Pull request merged**
